global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: /metrics

  # OpenTelemetry Collector exporter metrics
  - job_name: 'otel-collector-exporter'
    static_configs:
      - targets: ['otel-collector:8889']
    metrics_path: /metrics

  # Weaviate metrics (if running locally)
  - job_name: 'weaviate'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /metrics
    scrape_interval: 5s 